name: Build

on: push

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci-skip') && contains(github.event.head_commit.message, 'ci-build')"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-10.14]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libasound2-dev libgtk-3-dev libwebkit2gtk-4.0-dev
      
      - name: Cargo Update
        uses: actions-rs/cargo@v1
        with:
          command: update
      
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release  --verbose
      
      - name: Upload Non-Windows Built Binary
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v1
        with:
          name: soundsense-rs-${{runner.os}}
          path: target/release/soundsense-rs

      - name: Upload Windows Built Binary
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v1
        with:
          name: soundsense-rs-${{runner.os}}
          path: target/release/soundsense-rs.exe


      - name: Version
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        id: version_id
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - name: Package release not Windows
        if: startsWith(github.ref, 'refs/tags/v') && runner.os != 'Windows'
        run: tar cjf soundsense-rs-${{ steps.version_id.outputs.VERSION }}-${{runner.os}}.tbz -C target/release/ soundsense-rs 
      - name: Package release win
        if: startsWith(github.ref, 'refs/tags/v') && runner.os == 'Windows'
        shell: bash
        run: 7z a soundsense-rs-${{ steps.version_id.outputs.VERSION }}-Windows.zip ./target/release/soundsense-rs.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          body: |
            Files generated by github action
          files: |
            soundsense-rs-*-*.tbz
            soundsense-rs-*-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
